SCMOD-7512: Adding some important debug logging
CAFDataProcessing/worker-markup pull request #48
Opened 2019-09-12 18:12 UTC by rahul-kulkarni73

https://portal.digitalsafe.net/browse/SCMOD-7512

2019-09-12 19:15 UTC, dermot-hardy requested changes
You need to use parameterized logging or otherwise avoid the cost of the parameter construction.  As it is this change will cause significant overhead even when debug mode is not on, because it will always do all the internal processing you've added before it checks the log level.

See https://logback.qos.ch/manual/architecture.html#parametrized.

> The following two lines will yield the exact same output. However, in case of a disabled logging statement, the second variant will outperform the first variant by a factor of at least 30.
> 
> logger.debug("The new entry is "+entry+".");
> logger.debug("The new entry is {}.", entry);

2019-09-12 19:45 UTC, rahul-kulkarni73 commented
Great information.

2019-09-13 10:51 UTC, dermot-hardy requested changes
This will avoid the cost of the string concatenation, but in these cases you've still got a significant cost for the construction of those parameters - you need to either create a wrapper object or use the `.isDebugEnabled()` method.

2019-09-16 12:51 UTC, dermot-hardy approved these changes

2019-09-16 12:51 UTC, dermot-hardy commented on worker-markup-core/src/main/java/com/github/cafdataprocessing/worker/markup/core/MarkupDocumentEngine.java
> +                    (doc));
Odd place the break the line.

2019-09-16 12:57 UTC, rahul-kulkarni73 commented on worker-markup-core/src/main/java/com/github/cafdataprocessing/worker/markup/core/MarkupDocumentEngine.java
> +                    (doc));
Intellij :)

2019-09-16 12:58 UTC, merged